mysql:
  image: appsembler/edx-multi-mysql
mongodb:
  image: appsembler/edx-multi-mongodb
forum:
  image: appsembler/edx-multi-forum
  links:
    - mongodb:mongo
edxapp:
  image: appsembler/edx-multi-edxapp
  command: /root/init.sh
  ports:
    - 80
    - 18010
    - 18020
  links:
    - mysql:db
    - mongodb:mongo
    - forum
  tty: true
