EDXAPP_PLATFORM_NAME: 'Docker'
EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_ENV: 'lms.envs.docker_multi'
EDXAPP_CMS_ENV: 'cms.envs.docker_multi'
EDXAPP_WORKERS:
  lms: 2
  cms: 1

# MySQL
EDXAPP_MYSQL_DB_NAME: 'edxapp'
EDXAPP_MYSQL_USER: 'edxapp'
EDXAPP_MYSQL_PASSWORD: 'Wuk8faewae'
EDXAPP_MYSQL_USER_HOST: '%'
EDXAPP_MYSQL_HOST: 'mysql'
EDXAPP_MYSQL_PORT: '3306'
EDXAPP_MYSQL_USER_ADMIN: "{{ EDXAPP_MYSQL_USER }}"
COMMON_MYSQL_MIGRATE_USER: "{{ EDXAPP_MYSQL_USER }}"
COMMON_MYSQL_MIGRATE_PASS: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_PASSWORD_READ_ONLY: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_PASSWORD_ADMIN: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_PASSWORD_MIGRATE: "{{ EDXAPP_MYSQL_PASSWORD }}"

# Mongo DB
EDXAPP_MONGO_HOSTS: ['mongodb']
EDXAPP_MONGO_PORT: "27017"
EDXAPP_MONGO_DB_NAME: 'docker-edxapp'
EDXAPP_MONGO_USER: 'edxapp'
EDXAPP_MONGO_PASSWORD: 'daheiYae2c'
MONGO_BIND_IP: '0.0.0.0'

# Forum
EDXAPP_COMMENTS_SERVICE_URL:  'http://forum:18080'
EDXAPP_COMMENTS_SERVICE_KEY: 'azuaWoh3Qu'
