---
runit_lite_services:
  - elasticsearch
  - memcached
  - mongodb
  - mysql
  - nginx
  - supervisor
  - supervisor.devpi

runit_full_services:
  - elasticsearch
  - forum
  - memcached
  - mongodb
  - mysql
  - nginx
  - rabbitmq-server
  - redis-server
  - supervisor
  - supervisor.devpi

runit_lite_services_stop:
  - mysql

runit_full_services_stop:
  - mysql
  - rabbitmq-server

version: full
supervisor_version: full
