- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "no"
    openid_workaround: True
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    edx_platform_version: 'docker_release'
  roles:
    - { role: 'docker', runit_service: 'supervisor', supervisor_version: 'solo' }
    - { role: 'docker', runit_service: 'supervisor.devpi' }
    - { role: 'docker', runit_service: 'nginx' }
    - role: nginx
      nginx_sites:
      - lms
      - cms
      nginx_default_sites:
      - lms
    - edxapp
    - { role: 'docker', runit_service: 'nginx' }
    - { role: 'docker', runit_service: 'supervisor.devpi' }
    - { role: 'docker', runit_service: 'supervisor', supervisor_version: 'solo' }
