---

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/ora/defaults/main.yml
    - roles/analytics_api/defaults/main.yml
  roles:
    - edxlocal
    - { role: 'docker', runit_service: 'mysql' }
    - { role: 'docker', runit_service: 'memcached' }
